from scripts.routes import *

os.mkdir(f'{work_directory}\\factory')
os.mkdir(start_storage)
os.mkdir(end_storage)
os.mkdir(drying_capacity)
os.mkdir(sulfur_boiler)
os.mkdir(first_contact_device)
os.mkdir(first_absorption_capacity)
os.mkdir(second_contact_device)
os.mkdir(second_absorption_capacity)
os.mkdir(mixing_capacity)
os.mkdir(intermediate_capacity)
os.mkdir(ammonia_evaporator)
os.mkdir(ammonia_air_mixer)
os.mkdir(steam_turbine)
os.mkdir(contact_device)
os.mkdir(steam_boiler_utilizer)
os.mkdir(refrigerator_condenser)
os.mkdir(absorption_tank)
os.mkdir(package)
os.mkdir(f'{package}\\package_H2SO4')
os.mkdir(f'{package}\\package_HNO3')
